// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebRestaurantManagement.Context;

#nullable disable

namespace WebRestaurantManagement.Entities
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241021212150_InItRes")]
    partial class InItRes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebRestaurantManagement.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MealsCount")
                        .HasColumnType("integer");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("MenuId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuId = 1,
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = 2,
                            MenuId = 1,
                            Name = "Main Courses"
                        });
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ComplaintSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int?>("ReportId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_complaints");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReportId");

                    b.ToTable("Complaints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComplaintSource = "Very old bread",
                            CustomerId = 2,
                            Date = new DateOnly(2020, 1, 10)
                        });
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jashua"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Davron"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jasur"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Javlon"
                        });
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Describtion")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id")
                        .HasName("pk_meals");

                    b.HasIndex("CategoryId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Describtion = "Grilled bread with toppings",
                            Name = "Bruschetta",
                            Price = 5.5
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Describtion = "Toasted bread with garlic",
                            Name = "Garlic Bread",
                            Price = 3.5
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Describtion = "Chicken with herbs",
                            Name = "Grilled Chicken",
                            Price = 12.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Describtion = "Creamy pasta with bacon",
                            Name = "Pasta Carbonara",
                            Price = 8.5
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Describtion = "Grilled beef steak",
                            Name = "Steak",
                            Price = 15.0
                        });
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_menus");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Main menu"
                        });
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("OrderDateTime")
                        .HasColumnType("date");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportId")
                        .HasColumnType("integer");

                    b.Property<int>("WaiterId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReportId");

                    b.HasIndex("WaiterId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderDateTime = new DateOnly(2023, 10, 1),
                            WaiterId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            OrderDateTime = new DateOnly(2023, 10, 2),
                            WaiterId = 2
                        });
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double precision");

                    b.HasKey("OrderId", "MealId")
                        .HasName("pk_order_details");

                    b.HasIndex("MealId");

                    b.HasIndex("RecipeId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            MealId = 1,
                            Count = 2,
                            UnitPrice = 5.5
                        },
                        new
                        {
                            OrderId = 1,
                            MealId = 3,
                            Count = 1,
                            UnitPrice = 12.0
                        },
                        new
                        {
                            OrderId = 2,
                            MealId = 4,
                            Count = 1,
                            UnitPrice = 8.5
                        },
                        new
                        {
                            OrderId = 2,
                            MealId = 5,
                            Count = 2,
                            UnitPrice = 15.0
                        });
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double precision");

                    b.Property<int>("WaiterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplaintsCount")
                        .HasColumnType("integer");

                    b.Property<int>("OrdersCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("SalesDay")
                        .HasColumnType("date");

                    b.Property<double>("TotalSales")
                        .HasColumnType("double precision");

                    b.Property<int?>("WaiterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Waiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_waiters");

                    b.ToTable("Waiters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            HireDate = new DateOnly(2020, 1, 10),
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St",
                            HireDate = new DateOnly(2019, 5, 20),
                            Name = "Jane Smith"
                        });
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Category", b =>
                {
                    b.HasOne("WebRestaurantManagement.Models.Menu", "Menu")
                        .WithMany("Categories")
                        .HasForeignKey("MenuId")
                        .IsRequired()
                        .HasConstraintName("fk_menu_categories");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Complaint", b =>
                {
                    b.HasOne("WebRestaurantManagement.Models.Customer", "Customer")
                        .WithMany("Complaints")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_customer_complaints");

                    b.HasOne("WebRestaurantManagement.Models.Report", "Report")
                        .WithMany("Complaints")
                        .HasForeignKey("ReportId")
                        .HasConstraintName("fk_report_complaints");

                    b.Navigation("Customer");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Meal", b =>
                {
                    b.HasOne("WebRestaurantManagement.Models.Category", "Category")
                        .WithMany("Meals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meals_categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Order", b =>
                {
                    b.HasOne("WebRestaurantManagement.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fk_customer_orders");

                    b.HasOne("WebRestaurantManagement.Models.Report", "Report")
                        .WithMany("Orders")
                        .HasForeignKey("ReportId")
                        .HasConstraintName("fk_order_reports");

                    b.HasOne("WebRestaurantManagement.Models.Waiter", "Waiter")
                        .WithMany("Orders")
                        .HasForeignKey("WaiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_waiters");

                    b.Navigation("Customer");

                    b.Navigation("Report");

                    b.Navigation("Waiter");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.OrderDetail", b =>
                {
                    b.HasOne("WebRestaurantManagement.Models.Meal", "Meal")
                        .WithMany("OrderDetails")
                        .HasForeignKey("MealId")
                        .IsRequired()
                        .HasConstraintName("fk_order_details_meals");

                    b.HasOne("WebRestaurantManagement.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("fk_order_details_orders");

                    b.HasOne("WebRestaurantManagement.Models.Recipe", "Recipe")
                        .WithMany("OrderDetails")
                        .HasForeignKey("RecipeId");

                    b.Navigation("Meal");

                    b.Navigation("Order");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Recipe", b =>
                {
                    b.HasOne("WebRestaurantManagement.Models.Order", "Order")
                        .WithOne("Recipe")
                        .HasForeignKey("WebRestaurantManagement.Models.Recipe", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Category", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Customer", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Meal", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Menu", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Recipe", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Report", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Waiter", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
