// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebRestaurantManagement.Context;

#nullable disable

namespace WebRestaurantManagement.Entities
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebRestaurantManagement.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MealsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MealsCount = 2,
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = 2,
                            MealsCount = 3,
                            Name = "Main Courses"
                        });
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Describtion")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_meals");

                    b.HasIndex("CategoryId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Describtion = "Grilled bread with toppings",
                            Name = "Bruschetta"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Describtion = "Toasted bread with garlic",
                            Name = "Garlic Bread"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Describtion = "Chicken with herbs",
                            Name = "Grilled Chicken"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Describtion = "Creamy pasta with bacon",
                            Name = "Pasta Carbonara"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Describtion = "Grilled beef steak",
                            Name = "Steak"
                        });
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("OrderDateTime")
                        .HasColumnType("date");

                    b.Property<int>("WaiterId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("WaiterId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderDateTime = new DateOnly(2023, 10, 1),
                            WaiterId = 1
                        },
                        new
                        {
                            Id = 2,
                            OrderDateTime = new DateOnly(2023, 10, 2),
                            WaiterId = 2
                        });
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("MealId")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double precision");

                    b.HasKey("OrderId", "MealId")
                        .HasName("pk_order_details");

                    b.HasIndex("MealId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            MealId = 1,
                            Count = 2,
                            UnitPrice = 5.5
                        },
                        new
                        {
                            OrderId = 1,
                            MealId = 3,
                            Count = 1,
                            UnitPrice = 12.0
                        },
                        new
                        {
                            OrderId = 2,
                            MealId = 4,
                            Count = 1,
                            UnitPrice = 8.5
                        },
                        new
                        {
                            OrderId = 2,
                            MealId = 5,
                            Count = 2,
                            UnitPrice = 15.0
                        });
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Waiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("pk_waiters");

                    b.ToTable("Waiters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            HireDate = new DateOnly(2020, 1, 10),
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St",
                            HireDate = new DateOnly(2019, 5, 20),
                            Name = "Jane Smith"
                        });
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Meal", b =>
                {
                    b.HasOne("WebRestaurantManagement.Models.Category", "Category")
                        .WithMany("Meals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meals_categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Order", b =>
                {
                    b.HasOne("WebRestaurantManagement.Models.Waiter", "Waiter")
                        .WithMany("Orders")
                        .HasForeignKey("WaiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_waiters");

                    b.Navigation("Waiter");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.OrderDetail", b =>
                {
                    b.HasOne("WebRestaurantManagement.Models.Meal", "Meal")
                        .WithMany("OrderDetails")
                        .HasForeignKey("MealId")
                        .IsRequired()
                        .HasConstraintName("fk_order_details_meals");

                    b.HasOne("WebRestaurantManagement.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("fk_order_details_orders");

                    b.Navigation("Meal");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Category", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Meal", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WebRestaurantManagement.Models.Waiter", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
